### ISSUE TITLE
Residence time peaks in 2018 in imputed data

### ISSUE THREAD

**Issue by vgherard** [erahumed/erahumed#103]
Andreu's comment
> In 2018 imputed data, we see very high peaks in residence time. Why is this so?

We should review this, as it may be a symptom of some problem related with the GAM imputation approach @pabloamadorc.

**Comment by vgherard** [comment]
The peak actually occurs in 2017, see attached screenshot. In the same days, the outflow goes to zero and even becomes negative, due to negative values being predicted by the GAMs that reconstruct missing data in the measured outflows.

@pabloamadorc this is something we need to think about.


![image](https://github.com/user-attachments/assets/25229114-f007-4f58-bebb-2b83d408fd9f)

![image](https://github.com/user-attachments/assets/e876adbc-46b3-4b8e-9304-da05dc907fa8)

**Comment by pabloamadorc** [comment]
Podríamos hacer una revisión exhaustiva de las imputaciones, ya que fueron de las primeras cosas que hice con GAMs y en la tesis, y probablemente haya bastante margen de mejora. De todas formas, durante 2017 (y creo que también parte de 2018), los sensores dejaron de funcionar. Aunque mi enfoque funciona bien para días específicos, es cierto que los problemas se hacen mucho más evidentes al intentar simular un año completo.

**Comment by vgherard** [comment]
Superseded by [erahumed-meta#4](https://github.com/erahumed/erahumed-meta/issues/4)
