### ISSUE TITLE
Document the source of `albufera_clusters`

### ISSUE THREAD

**Issue by vgherard** [erahumed/erahumed#52]

**Comment by pabloamadorc** [comment]
"In this study, the rice production area of the ANP (210 km2) was divided into hydrological rice-production clusters. This was achieved by retrieving [cadastral](https://www.sciencedirect.com/topics/earth-and-planetary-sciences/cadastral) cartographic data from the government of Spain and filtering it to select only areas designated for rice cultivation. Based on cartographical data for the irrigation ditches of the Natural Park, polygons were created, and the ditches were segmented longitudinally every 500 m in accordance with those polygons. Then, the [centroid](https://www.sciencedirect.com/topics/earth-and-planetary-sciences/centroid) of the ditch segment was calculated. The rice paddies were clustered based on the Euclidean distance to the nearest centroid of the segmented ditch, resulting in 552 rice-production clusters. The steps followed to carry out this process are shown in the Supplementary Material (Fig. S1)." From Martinez-Megías et al., 2022

**Comment by vgherard** [comment]
Thanks @pabloamadorc , this is on my radar together with a few similar items (#50, #68, #61).

For this one, I think I have all the information I need. For the others I may ping you whenever I get to document this data. 😃
